{{- if or .Values.redisCluster.enabled .Values.keycloakInstance.enabled .Values.postgresCluster.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-operator-precheck
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
# CRDs are cluster-scoped; need ClusterRole to get/list them
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator-precheck
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-operator-precheck
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-operator-precheck
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-operator-precheck
    namespace: {{ .Release.Namespace }}
{{- end }}
