{{- if and .Values.monitoring.serviceMonitor.postgres.enabled .Values.monitoring.serviceMonitor.postgres.serviceNamespace }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: kairos-fullstack
    {{- with .Values.monitoring.serviceMonitor.postgres.release }}
    release: {{ . }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.monitoring.serviceMonitor.postgres.serviceNamespace }}
  selector:
    matchLabels:
      {{- (.Values.monitoring.serviceMonitor.postgres.serviceSelector | default (dict "app.kubernetes.io/name" "postgres") | toYaml) | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.postgres.interval }}
{{- end }}
